### ISSUE TITLE
LED Control 

### ISSUE THREAD

**Issue by cgarnold** [ovhpa/cudy_wu700_ac650#1]
Helo my friend , thank you for your great help, i have a ask for you, do you had a problem with  rtw_led_enable ?

**Comment by ovhpa** [comment]
Hello,
Sorry I didn't saw your message: it was a national holiday here, and for some reason github didn't send me a notification (or i didn't saw it).

Anyway, the cudy wu700 ac650 is a very cheap usb wifi dongle.
Unfortunately it doesn't have a LED, so I can't check about it, sorry m(_ _)m

Is there any trouble with rtw_led_enable?

**Comment by cgarnold** [comment]
ok no problem i tried again and it worked, thank u.
